### ISSUE TITLE
Loading local WASM (instead of CDN) file not working

### ISSUE THREAD

**Issue by GreenFlag31** [Sec-ant/zxing-wasm#162]
Hi. 

As the title says, it fails to load local file. If I try to set the path and test it with `
const zxingModulePromise1 = getZXingModule();`, it fails: 
![image](https://github.com/user-attachments/assets/41747a1f-b319-4fbd-b635-c988478b8f72)

I have seen the other [issue](https://github.com/Sec-ant/zxing-wasm/issues/95) regarding loading local files.

If I don't test it, it silences the error and still fetch the CDN:
![image](https://github.com/user-attachments/assets/4875d2c7-4503-4a42-a380-dd2028524711)

If I try this:
```javascript
// not implemented ??
setZXingModuleOverrides({
  locateFile: () => {
    return `file://${path.resolve(__dirname, '../src/assets/zxing_full.wasm')}`;
  },
});
```
 It returns an error "not implemented yet".

Could you either implement it or correct the error? Thanks

**Comment by Sec-ant** [comment]
I'm not very certain about what happened, but the `"invalid index ..."` error message looks to me like you're loading a mismatched version of the `.wasm` file. Where did you get the `zxing_full.wasm` and `zxing_reader.wasm` assets? And which version of `zxing-wasm` does your project currently depends on?

FWIW, the tests in this repo [uses a local `.wasm` file](https://github.com/Sec-ant/zxing-wasm/blob/9ccb982c301875ff9e54e709696576bfb680c217/tests/blackbox.test.ts#L83-L89) to run in the node.js runtime.

Also, I don't think the `"not implemented yet"` is from this repo.

**Comment by GreenFlag31** [comment]
"zxing-wasm": "^1.3.0".

"Where did you get the zxing_full.wasm and zxing_reader.wasm assets?"
* I got them from the CDN : https://fastly.jsdelivr.net/npm/zxing-wasm@1.3.0/dist/full/zxing_full.wasm

"FWIW, the tests in this repo uses a local .wasm file"
* Hmm, yes, and I saw that the wasm were present in the node_modules. So why fetching them from a CDN?

![image](https://github.com/user-attachments/assets/20965239-6d12-43c2-bdeb-36c1152544d2)


Same story with the local .wasm:
![image](https://github.com/user-attachments/assets/51b19ef3-74e9-4094-b46b-f1d87bbdc552)

**Comment by Sec-ant** [comment]
> * Hmm, yes, and I saw that the wasm were present in the node_modules. So why fetching them from a CDN?

You can if you use node + npm, but not every runtime/package manager has the `node_modules` folder or uses the same structure, e.g., yarn, pnpm, bun, deno ... And importing the wasm file from `node_modules` requires a bundle tool which doesn't exist when you just want to use `<script type="module">` on a web page.

I'm not sure what happened, maybe you can share the repo to reproduce this issue so I can take a look?

**Comment by Sec-ant** [comment]
I wonder if this is a server-side vs client-side issue? Do you use this package on the sever-side or the client side?

**Comment by GreenFlag31** [comment]
It's a node.js application, so it's obviously a server side issue.

Yes, I have opened a repo, but I think this issue is easily reproducible, this is a very basic Node.js express application.

Repo: [here](https://github.com/GreenFlag31/zxing-wasm)

**Comment by Sec-ant** [comment]
`zxing-wasm` implies `zxing-wasm/full`, it and `zxing-wasm/reader` are two separate entry points, so you should change your code like this, and they don't share the same module overrides.

```diff
--- a/src/qrcodes.ts
+++ b/src/qrcodes.ts
@@ -2,8 +2,7 @@ import { createCanvas, Image, ImageData, loadImage } from 'canvas';
 import { Router } from 'express';
 import { readFileSync } from 'fs';
 import path, { resolve } from 'path';
-import { getZXingModule, setZXingModuleOverrides } from 'zxing-wasm';
-import { readBarcodesFromImageData, type ReaderOptions } from 'zxing-wasm/reader';
+import { getZXingModule, setZXingModuleOverrides, readBarcodesFromImageData, type ReaderOptions } from 'zxing-wasm/reader';
 export const router = Router();
 
 const originalFetch = global.fetch;
@@ -13,7 +12,7 @@ global.fetch = async function (...args) {
 };
 
 setZXingModuleOverrides({
-  wasmBinary: readFileSync(resolve(__dirname, '../src/assets/zxing_full.wasm')),
+  wasmBinary: readFileSync(resolve(__dirname, '../src/assets/zxing_reader.wasm')),
 });
 
 getZXingModule();
```

**Comment by GreenFlag31** [comment]
Yop! Thanks a lot. It's resolved.
