### ISSUE TITLE
barcode-detector not mentioned

### ISSUE THREAD

**Issue by joleeee** [Sec-ant/zxing-wasm#180]
I wanted to use this but was about to give up because I found no example using the webcam. You should advertise `barcode-detector` in this repo too, and maybe mention "camera" and "barcode" as keywords.

**Comment by Sec-ant** [comment]
Yeah, probably I should, but `barcode-detector` doesn't have examples about using the webcam either 🫤. Currently camera is not in the scope of these two repos. Perhaps you want to take a look at some higher level repos like `vue-qrcode-reader`.

A react component was planned in this repo, but I got less and less time to complete it. Meanwhile, I'm also preparing a breaking major version change to encompass the latest code from `zxing-cpp` and `zint` 😩

**Comment by Sec-ant** [comment]
`barcode-detector` is now mentioned in the v2 README file: https://github.com/Sec-ant/zxing-wasm?tab=readme-ov-file#faq
