### ISSUE TITLE
RuntimeError happend on Node.js

### ISSUE THREAD

**Issue by JohnieXu** [Sec-ant/zxing-wasm#67]
When i use this lib on Node.js V16, an error happend as below.

my code:

```js
import { writeBarcodeToImageFile, setZXingModuleOverrides, readBarcodesFromImageFile } from 'zxing-wasm'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
/**
 * @type {import('node:process').process}
 */
import process from 'node:process'

// console.log(writeBarcodeToImageFile)

setZXingModuleOverrides({
  logReadFiles: true,
  locateFile: (a, prefix) => {
    if (a.endsWith('.wasm')) {
      const p1 = 'https://registry.npmmirror.com/zxing-wasm/1.2.1/files/dist/full/zxing_full.wasm'
      return p1
    }
    return prefix + a
  }
})

/**
 * save blob to local file
 * @param {Blob} blob
 * @param {String} path
 */
function saveBlob2File(blob, path) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => {
      const buffer = Buffer.from(reader.result)
      writeFile(path, buffer).then(resolve, reject)
    }
    reader.onerror = reject
    reader.readAsArrayBuffer(blob)
  })
}

for (let i = 0; i < 1; i++) {
  const content = Date.now() + '' + i
  writeBarcodeToImageFile(content, {
    format: ['QRCode', 'Code128']
  }).then(res => {
    if (res.error) {
      console.log(res.error)
    } else {
      saveBlob2File(res.image, path.resolve(process.cwd(), './outputs/' + content))
    }
  }).catch(console.log)
}
```

got the error:
```text
PS E:\projects\demo\zxing-wasm-demo\node> npm start

> node@1.0.0 start
> node index.js   

failed to asynchronously prepare wasm: both async and sync fetching of the wasm failed
Aborted(both async and sync fetching of the wasm failed)
RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.
    at de (file:///E:/projects/demo/zxing-wasm-demo/node_modules/zxing-wasm/dist/es/full/index.js:70:15)      
    at file:///E:/projects/demo/zxing-wasm-demo/node_modules/zxing-wasm/dist/es/full/index.js:93:59
```

node version: `v16.13.1`

**Comment by Sec-ant** [comment]
This package utilizes some of the APIs that are only present in the latest versions of Node: `fetch`, `ReadableStream`, `Blob`, .etc. As [Node 16 is no longer maintained officially](https://nodejs.org/en/about/previous-releases), I will not put extra efforts to keep its compatibility with 16, so this works is handed over to the package consumers to polyfill the APIs manually, or update the Node runtime to the latest version.

FWIW, I don't think you can use the `FileReader` in a Node program either. And there's a mistake in your `writeBarcodeToImageFile` function, in which the `format` option should accept a string, not an array.

**Comment by JohnieXu** [comment]
> This package utilizes some of the APIs that are only present in the latest versions of Node: `fetch`, `ReadableStream`, `Blob`, .etc. As [Node 16 is no longer maintained officially](https://nodejs.org/en/about/previous-releases), I will not put extra efforts to keep its compatibility with 16, so this work is handed over to the package consumers to polyfill the APIs manually, or update the Node runtime to the latest version.
> 
> FWIW, I don't think you can use the `FileReader` in a Node program either. And there's a mistake in your `writeBarcodeToImageFile` function, in which the `format` option should accept a string, not an array.

Thanks u, I found it works finely on Node v18.19.0 today. btw, thanks for note that mine mistake on FileReader.
