### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './' is not defined by "exports" in project/node_modules/zxing-wasm/package.json

### ISSUE THREAD

**Issue by carafelix** [Sec-ant/zxing-wasm#94]
Running the code snippet from the readme;
I was able to run by changing the import path to "../node_modules/zxing-wasm/dist/cjs/full/index";
This project looks awesomely structured! great work

**Comment by Sec-ant** [comment]
Can you do a quick check if changing `"."` to `"./"` in this line in [`package.json`](https://github.com/Sec-ant/zxing-wasm/blob/main/package.json) as suggested by the error message solves your problem?

https://github.com/Sec-ant/zxing-wasm/blob/c1823c22c8884b7b9ece20bb784be69b9b52c402/package.json#L11

**Comment by carafelix** [comment]
if changing to ```"./"``` results in another error. There is no problems with ```"."``` if importing without the final ```/```, like so: ```from 'zxing-wasm'```
