### ISSUE TITLE
How to serve the .wasm from a local file instead of a CDN, for offline use.

### ISSUE THREAD

**Issue by carafelix** [Sec-ant/zxing-wasm#95]
It is possible to instruct `setZXingModuleOverrides` to locate the .wasm in a local directory? like returning `./src/to/.wasm/` ??

**Comment by Sec-ant** [comment]
Not sure what your use case and runtime would be, but here's a small demo to use it locally in node.

**File structure:**
```
.
├── index.js
├── node_modules
├── package-lock.json
├── package.json
└── zxing_reader.wasm
```

**`index.js`:**
```ts
import {
  setZXingModuleOverrides,
  readBarcodesFromImageFile,
} from "zxing-wasm/reader";

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

setZXingModuleOverrides({
  wasmBinary: readFileSync(
    fileURLToPath(new URL("./zxing_reader.wasm", import.meta.url)),
  ),
});

fetch(
  "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Hello%20world!",
)
  .then((resp) => resp.blob())
  .then(readBarcodesFromImageFile)
  .then(console.log);
```

**Comment by gfeller** [comment]
My solution:

setZXingModuleOverrides({
  locateFile : () => {
    return  "/assets/libs/zxing/zxing_full.wasm";
  }
});

**Comment by Sec-ant** [comment]
A more comprehensive answer in the v2 README: https://github.com/Sec-ant/zxing-wasm?tab=readme-ov-file#integrating-in-non-web-runtimes
